-- ====================================================================
-- CHOLGA RUN - DATABASE SCHEMA (v1.0.0)
-- This DDL script initializes the database for the Cholga Run leaderboard.
-- Run this script in the Supabase SQL Editor for your Staging/Production project.
-- ====================================================================

-- 1. Create the high-score leaderboard table
CREATE TABLE IF NOT EXISTS public.cholga_leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    score BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

    -- Add constraint to prevent empty or too long names in database level
    CONSTRAINT name_length_check CHECK (char_length(trim(name)) > 0 AND char_length(name) <= 12),
    -- Score must be positive
    CONSTRAINT positive_score CHECK (score >= 0)
);

-- 2. Create performance indices
-- The frontend leaderboard performs a fast top 10 query:
-- ORDER BY score DESC, created_at ASC LIMIT 10;
CREATE INDEX IF NOT EXISTS idx_cholga_leaderboard_high_scores 
ON public.cholga_leaderboard (score DESC, created_at ASC);

-- 3. Security Configuration (Row-Level Security)
-- Enable Row-Level Security (RLS) on the table
ALTER TABLE public.cholga_leaderboard ENABLE ROW LEVEL SECURITY;

-- Note on RLS and Serverless Functions:
-- The Vercel backend serverless function (api/high-score.js) utilizes the 
-- SUPABASE_SERVICE_ROLE_KEY (a superuser key) to read and write records.
-- Because of this, it bypasses RLS policies entirely, allowing it to perform 
-- validations in code (e.g. name sanitation, max length, negative scores) 
-- before committing data to the database. This is a secure backend-proxy pattern.
--
-- However, for audit compliance and future-proofing (in case you transition to 
-- client-side RPC/direct reads via the SUPABASE_ANON_KEY), we declare the 
-- following basic read policy:

CREATE POLICY "Allow public read access to leaderboard" 
ON public.cholga_leaderboard 
FOR SELECT 
USING (true);

-- By leaving INSERT/UPDATE policies omitted for public/anon roles, direct client-side
-- writes are blocked by default, ensuring all writes MUST go through the secure Vercel API.
